name: Auto Activity

on:
  schedule:
    - cron: '10-50 7 * * 1-5'  # Понедельник - Пятница, запуск в случайное время 07:10-08:50 UTC
    - cron: '10-50 8 * * 6'    # Суббота, запуск в случайное время 08:10-09:50 UTC

  workflow_dispatch:

jobs:
  activity:
    runs-on: ubuntu-latest
    steps:
      - name: Set random delay
        run: sleep $(( ( RANDOM % 6000 ) + 1 ))  # Задержка от 1 до 6000 секунд (100 минут)

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "Vita"
          git config --global user.email "197509342+Vita689479@users.noreply.github.com"

      - name: Generate random activity
        run: |
          ACTION=$(( RANDOM % 3 ))
          
          if [[ $ACTION -eq 0 ]]; then
            echo "Committing a random change"
            echo "Random update $(date)" >> activity_log.txt
            git add activity_log.txt
            git commit -m "Random update at $(date)"
            git push
          
          elif [[ $ACTION -eq 1 ]]; then
            echo "Creating a new GitHub Issue"
            gh issue create --title "Automated Issue $(date)" --body "This is a randomly generated issue."
          
          else
            echo "Adding a comment to an issue"
            ISSUE_NUMBER=$(gh issue list --state open --json number --jq '.[0].number')
            if [[ -n "$ISSUE_NUMBER" ]]; then
              gh issue comment $ISSUE_NUMBER --body "Automated comment at $(date)"
            else
              echo "No open issues found"
            fi
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
