# Random Advice Bot
HEAD
Этот репозиторий содержит простой Python-бот, который получает случайные советы из интернета и выводит их в консоль.
## Установка
```sh
pip install requests
```
## Использование
```sh
python main.py
```
1c3838ab46d709552e6abf16ab7c04c28c7ba25d
